# Generated by Django 4.2.7 on 2023-11-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='basicNeed',
            field=models.BooleanField(max_length=1, null=True, verbose_name='Nececidad Basica'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='store',
            field=models.CharField(max_length=20, verbose_name='Almacen'),
        ),
    ]
