# Generated by Django 4.2.7 on 2023-11-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='make',
            field=models.CharField(max_length=50, verbose_name='marca'),
        ),
    ]
