# Generated by Django 4.2.7 on 2023-11-14 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial_precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha Consulta')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('priceUnit', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Precio Unidad')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='productos.productos')),
            ],
            options={
                'verbose_name': 'Historial Precio',
            },
        ),
    ]
