# Generated by Django 4.2.7 on 2023-11-14 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_staff'),
        ('productos_seleccionados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos_seleccionados',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
